-- MySQL Script generated by MySQL Workbench
-- Wed Oct  9 07:32:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema share_your_food
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema share_your_food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `share_your_food` DEFAULT CHARACTER SET utf8 ;
USE `share_your_food` ;

-- -----------------------------------------------------
-- Table `share_your_food`.`eating_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `share_your_food`.`eating_houses` (
  `house_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `owner_first_name` VARCHAR(32) NULL,
  `owner_last_name` VARCHAR(32) NULL,
  `street_name` VARCHAR(64) NULL,
  `house_number` VARCHAR(8) NULL,
  `postal_code` VARCHAR(6) NULL,
  `city_name` VARCHAR(32) NULL,
  PRIMARY KEY (`house_id`),
  UNIQUE INDEX `ideating_house_UNIQUE` (`house_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `share_your_food`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `share_your_food`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(32) NULL,
  `last_name` VARCHAR(32) NULL,
  `password` VARCHAR(64) NULL,
  `email` VARCHAR(256) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
